### ISSUE TITLE
ANR receiving push when AutoPilot is not ready

### ISSUE THREAD

**Issue by luispereira** [urbanairship/android-library#56]
I verified that my application every time I receive a push and AutoPilot is not ready the app has an ANR here are the logs:

```
E/ActivityManager: ANR in com.android.myapp
                                                PID: 14253
                                                Reason: Broadcast of Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x1000010 pkg=com.android.myapp cmp=com.android.myapp/com.urbanairship.push.gcm.GcmPushReceiver (has extras) }
                                                Load: 8.07 / 7.78 / 7.6
                                                CPU usage from 87622ms to 0ms ago (2018-02-15 12:15:35.065 to 2018-02-15 12:17:02.687):
                                                  8.7% 766/system_server: 5.7% user + 2.9% kernel / faults: 27817 minor 4 major
                                                  8.2% 428/surfaceflinger: 5% user + 3.2% kernel / faults: 5337 minor
                                                  6.1% 580/media.codec: 1.8% user + 4.3% kernel / faults: 229 minor
                                                  4.4% 13951/app_process32: 2.3% user + 2% kernel / faults: 634 minor
                                                  2.7% 1266/com.android.systemui: 1.9% user + 0.7% kernel / faults: 7839 minor 183 major
                                                  2.2% 12461/adbd: 0.4% user + 1.8% kernel / faults: 6652 minor
                                                  1.1% 570/installd: 0.1% user + 0.9% kernel / faults: 4539 minor
                                                  1% 13133/com.android.settings: 0.8% user + 0.2% kernel / faults: 19700 minor 46 major
                                                  1.5% 3563/com.estrongs.android.pop: 1.3% user + 0.2% kernel / faults: 3683 minor 9 major
                                                  1.4% 2907/com.google.android.gms.persistent: 0.9% user + 0.4% kernel / faults: 6298 minor 65 major
                                                  1% 268/mmcqd/0: 0% user + 1% kernel
                                                  0.5% 2491/com.google.android.googlequicksearchbox:search: 0.4% user + 0% kernel / faults: 12794 minor 183 major
                                                  0.7% 563/audioserver: 0.2% user + 0.5% kernel / faults: 392 minor 1 major
                                                  0.8% 10/rcu_preempt: 0% user + 0.8% kernel
                                                  0.8% 8864/mdss_fb0: 0% user + 0.8% kernel
                                                  0.5% 135/kswapd0: 0% user + 0.5% kernel
                                                  0.4% 6262/com.google.android.googlequicksearchbox: 0.3% user + 0.1% kernel / faults: 3852 minor 16 major
                                                  0.6% 7914/com.google.android.packageinstaller: 0.4% user + 0.1% kernel / faults: 2490 minor 3 major
                                                  0.5% 176/kgsl_worker_thr: 0% user + 0.5% kernel
                                                  0.4% 32574/kworker/u12:7: 0% user + 0.4% kernel
                                                  0.4% 12199/kworker/0:3: 0% user + 0.4% kernel
                                                  0.4% 296/msm-core:sampli: 0% user + 0.4% kernel
                                                  0.4% 3232/com.google.android.gms: 0.3% user + 0% kernel / faults: 5170 minor 30 major
                                                  0.3% 1247/com.google.android.inputmethod.latin: 0.2% user + 0% kernel / faults: 5850 minor 20 major
                                                  0.3% 3/ksoftirqd/0: 0% user + 0.3% kernel
                                                  0.3% 15/ksoftirqd/1: 0% user + 0.3% kernel
                                                  0.3% 469/irq/215-fc38800: 0% user + 0.3% kernel
                                                  0.3% 262/cfinteractive: 0% user + 0.3% kernel
                                                  0.2% 267/nanohub: 0% user + 0.2% kernel
                                                  0.2% 358/logd: 0.1% user + 0.1% kernel / faults: 84 minor
                                                  0.2% 4744/com.android.chrome:sandboxed: 0.2% user + 0% kernel / faults: 302 minor 10 major
                                                  0.2% 20/ksoftirqd/2: 0% user + 0.2% kernel
                                                  0.2% 25/ksoftirqd/3: 0% user + 0.2% kernel
                                                  0.1% 8858/kworker/u13:1: 0% user + 0.1% kernel
                                                  0.2% 202/spi7: 0% user + 0.2% kernel
                                                  0.1% 66/system: 0% user + 0.1% kernel
                                                  0.1% 53/kworker/u13:0: 0% user + 0.1% kernel
                                                  0.1% 424/msm_irqbalance: 0% user + 0.1% kernel / faults: 6 minor
                                                  0.1% 555/perfd: 0% user + 0.1% kernel / faults: 206 minor
                                                  0.1% 1318/kworker/u13:2: 0% user + 0.1% kernel
                                                  0.1% 13870/kworker/u13:7: 0% user + 0.1% kernel
                                                  0.1% 7113/kworker/u13:9: 0% user + 0.1% kernel
                                                  0% 10385/com.google.android.inputmethod.latin:train: 0% user + 0% kernel / faults: 3708 minor
                                                  0.1% 12561/logcat: 0% user + 0% kernel / faults: 23 minor
                                                  0.1% 319/ueventd: 0.1% user + 0% kernel
                                                  0.1% 420/android.hardware.wifi@1.0-service: 0% user + 0.1% kernel / faults: 54 minor
                                                  0.1% 1151/VosMCThread: 0% user + 0.1% kernel
                                                  0.1% 13747/kworker/1:1: 0% user + 0.1% kernel
                                                  0.1% 8933/kworker/u13:5: 0% user + 0.1% kernel
                                                  0.1% 10964/kworker/u13:6: 0% user + 0.1% kernel
                                                  0.1% 12936/kworker/u12:3: 0% user + 0.1% kernel
                                                  0.1% 6/kworker/u12:0: 0% user + 0.1% kernel
                                                  0% 418/android.hardware.graphics.allocator@2.0-service: 0% user + 0% kernel / faults: 78 minor
                                                  0% 8589/kworker/u12:5: 0% user + 0% kernel
                                                  0% 12935/kworker/u12:2: 0% user + 0% kernel
                                                  0% 359/servicemanager: 0% user + 0% kernel / faults: 20 minor
                                                  0.1% 558/thermal-engine: 0% user + 0% kernel / faults: 14 minor
                                                  0.1% 6718/kworker/2:2: 0% user + 0.1% kernel
                                                  0% 14125/kworker/u13:8: 0% user + 0% kernel
                                                  0% 8/rcuc/0: 0% user + 0% ke
02-15 12:17:07.625 766-776/? I/WifiService: getWifiApEnabledState uid=1000
```

**Comment by marc-scig** [comment]
HI there,

Are you working with a subclass of Autopilot in your project, and if so could you share some of your code?

**Comment by frochaguilherme** [comment]
Hi,

This happens after a CLEAN DATA to be performed.
When we restart the application and the autopilot is not ready, we receive a push notification the app has the ANR.

I was suppose that when a CLEAN DATA is performed, the UA also clean your channelID and your inside info, but the com.urbanairship.push.gcm.GcmPushReceiver receive a broadcast (that is sent from UA Dashboard for channelID) and make a ANR in app.

**Comment by marc-scig** [comment]
Thanks for the feedback, we'll look into it. Can you provide your Autopilot class and the full ANR logs? That will help us figure out where the deadlock is.

**Comment by frochaguilherme** [comment]
Hi there,

The full ANR logs are:

`02-27 11:50:15.269 766-780/? E/ActivityManager: ANR in com.android.myapp
                                                PID: 1899
                                                Reason: Broadcast of Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x1000010 pkg=com.android.myapp cmp=com.android.myapp/com.urbanairship.push.gcm.GcmPushReceiver (has extras) }
                                                Load: 7.18 / 8.32 / 8.34
                                                CPU usage from 0ms to 5006ms later (2018-02-27 11:50:10.231 to 2018-02-27 11:50:15.237):
                                                  31% 766/system_server: 17% user + 14% kernel / faults: 1542 minor
                                                  10% 9720/com.estrongs.android.pop: 7.6% user + 2.6% kernel / faults: 891 minor 5 major
                                                  3.8% 1416/com.android.phone: 2.8% user + 1% kernel / faults: 337 minor
                                                  3.6% 11522/com.android.systemui: 2.2% user + 1.4% kernel / faults: 342 minor
                                                  2.8% 1899/com.android.myapp: 2.2% user + 0.6% kernel / faults: 259 minor
                                                  0.1% 5190/com.google.android.inputmethod.latin: 0.1% user + 0% kernel / faults: 306 minor
                                                  2.2% 2907/com.google.android.gms.persistent: 1.8% user + 0.4% kernel / faults: 100 minor 1 major
                                                  1.9% 10/rcu_preempt: 0% user + 1.9% kernel
                                                  0.1% 2976/com.android.nfc: 0% user + 0% kernel / faults: 303 minor 1 major
                                                  0.1% 580/media.codec: 0% user + 0% kernel / faults: 1004 minor
                                                  0.1% 2963/com.quicinc.cne.CNEService: 0% user + 0% kernel / faults: 256 minor
                                                  0% 2991/com.qualcomm.qti.rcsbootstraputil: 0% user + 0% kernel / faults: 243 minor
                                                  0% 3002/com.qualcomm.qti.rcsimsbootstraputil: 0% user + 0% kernel / faults: 254 minor 1 major
                                                  1% 262/cfinteractive: 0% user + 1% kernel
                                                  1% 31574/adbd: 0.4% user + 0.6% kernel / faults: 168 minor
                                                  0.8% 358/logd: 0.4% user + 0.4% kernel
                                                  0.6% 296/msm-core:sampli: 0% user + 0.6% kernel
                                                  0.6% 469/irq/215-fc38800: 0% user + 0.6% kernel
                                                  0.6% 31250/kworker/u12:7: 0% user + 0.6% kernel
                                                  0.3% 3/ksoftirqd/0: 0% user + 0.3% kernel
                                                  0.3% 15/ksoftirqd/1: 0% user + 0.3% kernel
                                                  0.3% 20/ksoftirqd/2: 0% user + 0.3% kernel
                                                  0.4% 428/surfaceflinger: 0% user + 0.4% kernel / faults: 24 minor
                                                  0% 574/media.extractor: 0% user + 0% kernel / faults: 649 minor
                                                  0% 590/tombstoned: 0% user + 0% kernel
                                                  0% 1//init: 0% user + 0% kernel
                                                  0.1% 8/rcuc/0: 0% user + 0.1% kernel
                                                  0.1% 13/rcuc/1: 0% user + 0.1% kernel
                                                  0.1% 25/ksoftirqd/3: 0% user + 0.1% kernel
                                                  0.2% 53/kworker/u13:0: 0% user + 0.2% kernel
                                                  0% 135/kswapd0: 0% user + 0% kernel
                                                  0% 166/hwrng: 0% user + 0% kernel
                                                  0.2% 202/spi7: 0% user + 0.2% kernel
                                                  0.2% 267/nanohub: 0% user + 0.2% kernel
                                                  0.2% 268/mmcqd/0: 0% user + 0.2% kernel
                                                  0.2% 420/android.hardware.wifi@1.0-service: 0.2% user + 0% kernel
                                                  0% 425/lmkd: 0% user + 0% kernel
                                                  0.2% 563/audioserver: 0% user + 0.2% kernel / faults: 26 minor
                                                  0% 568/cameraserver: 0% user + 0% kernel / faults: 65 minor
                                                  0% 572/mediadrmserver: 0% user + 0% kernel / faults: 178 minor 3 major
                                                  0.2% 579/wificond: 0.2% user + 0% kernel
                                                  0.2% 1151/VosMCThread: 0% user + 0.2% kernel
                                                  0.2% 1931/logcat: 0% user + 0.2% kernel
                                                  0% 3534/com.android.bluetooth: 0% user + 0% kernel / faults: 65 minor
                                                  0.2% 29371/kworker/u12:1: 0% user + 0.2% kernel
                                                27% TOTAL: 16% user + 9.9% kernel + 0.4% iowait + 0.6% irq + 0.1% softirq
                                                CPU usage from 77ms to 585ms later (2018-02-27 11:50:10.308 to 2018-02-27 11:50:10.817) with 99% awake:
                                                  52% 766/system_server: 9.6% user + 43% kernel / faults: 483 minor
                                                    48% 780/ActivityManager: 7.2% user + 40% kernel
                                                    2.4% 901/SensorService: 2.4% user + 0% kernel
                                                    2.4% 941/WifiStateMachin: 2.4% user + 0% kernel
                                                    2.4% 945/IpManager.wlan0: 2.4% user + 0% kernel
                                                  2.1% 262/cfinteractive: 0% user + 2.1% kernel
                                                  2.2% 469/irq/215-fc38800: 0% user + 2.2% kernel
                                                  2.7% 9720/com.estrongs.android.pop: 2.7% user + 0% kernel / faults: 16 minor
                                                    2.7% 9823/Thread 2001 (Ac: 2.7% user + 0% kernel
                                                22% TOTAL: 10% user + 12% kernel`

**Comment by luispereira** [comment]
Hi @marc-scig do you have any news about this issue?

**Comment by marc-scig** [comment]
Hey @luispereira, @frochaguilherme, we're still trying to figure out what's going on.

When I say "full ANR logs" I mean stuff that would include a stack trace of what's causing the main thread to hang. These logs above only show CPU usage. Sorry it's such a pain to debug. See this android developer article on how to pull a trace file, which should help identify what the main thread was doing around the time the ANR happens:

https://developer.android.com/topic/performance/vitals/anr.html#diagnosing_anrs

**Comment by rlepinski** [comment]
@luispereira Looking into it now. I hope to have a release early next week.

**Comment by rlepinski** [comment]
Fixed in 9.0.2

**Comment by filipebatista** [comment]
This issue is still reproducible in 9.0.2 .  
Using the UrbainAirship lib 9.0.2 i was able to see an ANR when I receive a push and AutoPilot was not ready

**Comment by rlepinski** [comment]
@filipebatista I am unable to reproduce. Could you provide logs? Is the `isReady` method returning immediately? How are you using the isReady method? When I send a push with autopilot not being ready I get `E/UALib: Unable to process push, Airship is not ready.`

**Comment by filipebatista** [comment]
After having a valid channelId, i clear the application data and then open the application again but not perform the takeoff.

Then a try i to send a push notification to previous valid channelId .
When i see the entry log entry saying:
`I/Urban Airship Autopilot: Autopilot not ready.`

At this moment if i try to interact with the application, it does not respond until i see the log entry:

`Unable to process push, Airship is not ready. Make sure takeOff is called by either using autopilot or by calling takeOff in the application's onCreate method.`

Here is a part of the `/data/anr/traces.txt` file pulled from the device 

```
suspend all histogram:	Sum: 5.448ms 99% C.I. 3us-3459.519us Avg: 236.869us Max: 3718us
DALVIK THREADS (17):
"Signal Catcher" daemon prio=5 tid=2 Runnable
  | group="system" sCount=0 dsCount=0 obj=0x32c070a0 self=0xac7ed900
  | sysTid=23980 nice=0 cgrp=top_visible sched=0/0 handle=0xf3e14930
  | state=R schedstat=( 5240417 164218 13 ) utm=0 stm=0 core=4 HZ=100
  | stack=0xf3d18000-0xf3d1a000 stackSize=1014KB
  | held mutexes= "mutator lock"(shared held)
  (no managed stack frames)

"main" prio=5 tid=1 TimedWaiting
  | group="main" sCount=1 dsCount=0 obj=0x73e51f60 self=0xab7b6ce0
  | sysTid=23972 nice=-1 cgrp=top_visible sched=0/0 handle=0xf731ab50
  | state=S schedstat=( 5178555109 2793620174 11444 ) utm=424 stm=93 core=4 HZ=100
  | stack=0xff181000-0xff183000 stackSize=8MB
  | held mutexes=
  at java.lang.Object.wait!(Native method)
  - waiting on <0x06d3da11> (a java.lang.Object)
  at java.lang.Object.wait(Object.java:423)
  at com.urbanairship.UAirship.waitForTakeOff(UAirship.java:188)
  - locked <0x06d3da11> (a java.lang.Object)
  at com.urbanairship.push.PushService.onStartCommand(PushService.java:30)
  at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3047)
  at android.app.ActivityThread.access$2200(ActivityThread.java:165)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:150)
  at android.app.ActivityThread.main(ActivityThread.java:5621)
  at java.lang.reflect.Method.invoke!(Native method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

(...)
```

**Comment by rezonant** [comment]
We are experiencing similar ANRs stemming from a wait lock within waitForTakeOff on `9.1.0` on our app. Stack trace looks nearly identical to the one @filipebatista posted. I think the issue should be reopened.

**Comment by rlepinski** [comment]
@rezonant by similar do you mean a root of GcmPushReceiver ? If so, please update to 9.4.0 as it will no longer wait for the push to be completed before finishing the broadcast to avoid the ANR.
